### ISSUE TITLE
Slack / GitHub Sidebar Link Improvements

### ISSUE THREAD

**Issue by KrisJordan** [unc-csxl/csxl.unc.edu#267]
For the icons in the footer, @ajaygandecha's CR feedback was on point: we should use vector graphics and ideally we should try to make use of the already existing shared `SocialMediaIcon` widget: `frontend/src/app/shared/social-media-icon`

Additionally, let's add tooltips to the buttons in the sidebar to explain what the icons are for people who are new to slack and/or github.

For the Slack button:

"Join the CS XL Slack Chat Community" 

For the GitHub button:

"Contribute to the csxl.unc.edu Source Code on GitHub"

**Comment by krohan03** [comment]
### Progress:

- Old bottom buttons and icons replaced by `SocialMediaIcon` widget
- `SocialMediaIcon` widget modified to allow for `href` as optional argument when not provided (in order to allow `SocialMediaIcon` widget to be compatible with `(click)` methods)
- Added Slack icon as svg icon for `SocialMediaIcon` widget
- Added tooltips for buttons and styling for tooltips to not overflow over sidebar width
- Removed newly-deprecated code from #239 

### To-Do:

- Integrate #251: Feedback Buttons to add button to provide feedback into the bottom button bar in sidebar after issue completion
