### ISSUE TITLE
Improve Organization Slugs

### ISSUE THREAD

**Issue by jadekeegan** [unc-csxl/csxl.unc.edu#73]
# Improve Organization Slugs
Add a `short_name` field and generate slugs based on the organization abbreviations with regular expressions.

## Why?
This is important to ensuring that slugs are in the proper format to avoid spaces and other non-alphanumeric characters affecting the organization URL paths. Further, we can't just change the slugs to have hyphens because we use the slugs as short names on the organizations page. Most of the organizations have long names, so there would be many organizations with cut off names if we stopped using slugs as abbreviations.

## Acceptance Criteria
- [x] Add an `shorthand` field to the backend models and entities for Organization.
- [x] Add an `shorthand` field to the frontend models.
- [x] Update the organization page cards to use the `shorthand` field instead of the slug for organizations' with names that exceed the character limit of the card.
- [x] Create a method to convert `shorthand`s to slugs using regular expressions.

**Comment by KrisJordan** [comment]
I would perhaps encourage using `shorthand` (used in coworking https://github.com/unc-csxl/csxl.unc.edu/blob/c35b042113866ea5cc83ad4e4985e1ff35a0fafd/backend/entities/coworking/seat_entity.py#L23) or `short_name` rather than `abbreviation` which suggests taking first letters of words.

I do agree a shorthand name makes sense to separate out from slug which serves a different purpose.

We'll need to update the migration to include this field, as well.
